package sys.model;

public class ResourcesRoleKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources_role.resc_id
     *
     * @mbggenerated
     */
    private Integer rescId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources_role.role_id
     *
     * @mbggenerated
     */
    private Integer roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources_role
     *
     * @mbggenerated
     */
    public ResourcesRoleKey(Integer rescId, Integer roleId) {
        this.rescId = rescId;
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resources_role.resc_id
     *
     * @return the value of resources_role.resc_id
     *
     * @mbggenerated
     */
    public Integer getRescId() {
        return rescId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resources_role.role_id
     *
     * @return the value of resources_role.role_id
     *
     * @mbggenerated
     */
    public Integer getRoleId() {
        return roleId;
    }
}